server:
  port: 8085
spring:
  application:
    name: personnel-manager
  datasource: # 默认知道注解驱动
    # serverTimezone=UTC 解决时区问题，如果不加回报错
    # useSSL=false 解决SSL验证问题，如果不加会报警告
    url: jdbc:mysql://172.37.9.40:3306/manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC #
    username: ymb
    password: 123456
  resources:
    # 添加templates的下页面也可以直接通过浏览器访问，默认templates下的页面是不可以直接访问的
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  devtools:
    restart:
      enabled: true # 热部署生效
      additional-paths: src/main/java # 设置重启的目录
  thymeleaf:
    cache: false # 禁止浏览器缓存
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
IMAGE_SERVER_URL_PREFIX: http://localhost:8085 #客户端访问图片的前缀
LOCAL_DISK_LOCATION: classpath:templates #上传图片存放的位置